name: dartfx
description: A simple lightly function calculator for dart and javascript.
version: 1.0.12
repository: https://github.com/youngchan1988/dartfx
issue_tracker: https://github.com/youngchan1988/dartfx/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  intl: any
  analyzer: ^4.1.0
  convert: ^3.0.2
  crypto: ^3.0.2
  meta: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
